# Generated by Django 2.2.7 on 2019-11-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20191129_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='', max_length=200),
        ),
    ]
